name: Publish Python Package

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r requirements.txt

      - name: Build Package
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  # publish:
  #   name: Publish to PyPI
  #   needs: build

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: dist
  #         path: dist/

  #     - name: Publish distribution to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1

  release:
    name: Create GitHub Release
    needs: [build]

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Get Version
        run: |
          VERSION=$(awk -F' = ' '/version/ {gsub(/"/, "", $2); print $2; exit}' pyproject.toml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Delete existing release if it exists
        run: |
          gh release delete ${{ env.VERSION }} -y || echo "Release does not exist, continuing..."

      - name: Create GitHub Release
        id: create_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ env.VERSION }} dist/* --title "BrotherLabelPrinterControl v${{ env.VERSION }}" --generate-notes
