# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create Python Package

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: "6.x"

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build toml

      - name: Update version
        run: |
          python -c "
          import toml
          data = toml.load('pyproject.toml')
          data['tool']['poetry']['version'] = '${{ steps.gitversion.outputs.majorMinorPatch }}'
          with open('pyproject.toml', 'w') as f:
              toml.dump(data, f)
          "

      - name: Build package
        run: python -m build

      - uses: actions/upload-artifact@v4
        with:
          name: labelprinterkit
          path: |
            dist/labelprinterkit-*.whl
            dist/labelprinterkit-*.tar.gz
